# Plantar pressure meta-regression analysis
# Author: Scott Telfer
# Email: scott.telfer@gmail.com
# Last updated: 2018/08/02

# =============================================================================

## Import libraries
source("C:/Users/telfe/Dropbox/R Code/pkgTest.R")
packages <- c("metafor", "readr", "ggplot2", "dplyr")
lapply(packages, pkgTest)


# =============================================================================

## Helper functions
regions <- c("FF_PP", "MFF_PP", "Mid_FF_PP", "LFF_PP", "MF_PP", "MMF_PP", 
             "LMF_PP", "RF_PP", "MRF_PP", "LRF_PP", "M1_PP", "M2_PP", "M3_PP",
             "M4_PP", "M5_PP", "HLX_PP", "LT_PP")
regions_fs <- c("FF_PP", "MFF_PP", "Mid_FF_PP", "LFF_PP", "MF_PP", "MMF_PP", 
                "LMF_PP", "MRF_PP", "LRF_PP", "M1_PP", "M2_PP", "M3_PP",
                "M4_PP", "M5_PP", "HLX_PP", "LT_PP") 
meta_test <- function(meta_df, regions, moderators) {
  meta_test_results <- list()
  active_regions <- c()
  for (i in seq_along(regions)) {
    # filter for region
    meta_df_es <- meta_df %>% filter_(paste("!is.na(", regions[i], ")"))
    
    # Check if sufficent data for analysis
    if (nrow(meta_df_es) > 9) {
      # determine effect sizes
      meta_df_es <- escalc(measure = "MN", mi = get(regions[i]), 
                           sdi = get(paste0(regions[i], "_SD")), 
                           ni = Number, data = meta_df, 
                           slab = paste(First_Author, Year))
      
      # run meta regression
      f <- paste0("~ ", paste0(moderators, collapse = " + "))
      system_res_ME <- rma(yi, vi, mods = as.formula(f), data = meta_df_es, 
                           method = "REML")
      
      # save results
      active_regions <- c(active_regions, regions[i])
      meta_test_results[[(length(meta_test_results) + 1)]] <- system_res_ME
    }
  }

  # return list of model results
  names(meta_test_results) <- active_regions
  return(meta_test_results)
}


# =============================================================================

## Import data sheet
meta_data <- read_csv(paste0("C:/Users/telfe/Dropbox/My_Projects/", 
                             "Plantar_Pressure_Review/Plantar_Pressure_Review/", 
                             "PP_meta_data.csv"))

# remove empty rows (sometimes generated by excel)
meta_data <- meta_data[rowSums(is.na(meta_data))!=ncol(meta_data), ]


# Convert relevant columns to factors
cols <- c("Repeated", "Cohort_Type", "Footwear", "Activity", "System")

meta_data[cols] <- lapply(meta_data[cols], factor)


# =============================================================================

## Visualise raw data to check for issues
# Number of participants
boxplot(meta_data$Number, main = "Number of Participants")
summary(meta_data$Number)

# Percentage of participants who are female
boxplot(meta_data$Sex_Perc, main = "Percentage Female")
summary(meta_data$Sex_Perc)

# Age
boxplot(meta_data$Age, main = "Age")
summary(meta_data$Age)

# Height
boxplot(meta_data$Height, main = "Height")
summary(meta_data$Height)

# Mass
boxplot(meta_data$Mass, main = "Weight")
summary(meta_data$Mass)

# BMI
boxplot(meta_data$BMI, main = "BMI")
summary(meta_data$BMI)

# Speed
meta_data$Speed[meta_data$Speed == "SS"] <- NA # replace SS with NA
meta_data$Speed <- as.numeric(meta_data$Speed)
boxplot(meta_data$Speed, main = "Speed")
summary(meta_data$Speed)

## Visualize data to check for issues with disecrete variables
# Cohort type
barplot(table(meta_data$Cohort_Type))
levels(meta_data$Cohort_Type)

# Repeated
barplot(table(meta_data$Repeated))
levels(meta_data$Repeated)

# Footwear
barplot(table(meta_data$Footwear))
levels(meta_data$Footwear)

# System
barplot(table(meta_data$System))
levels(meta_data$System)


# =============================================================================

## data calculations
# BMI from height and weight
bmi_calc_index <- which(is.na(meta_data$BMI) & !is.na(meta_data$Height) 
                        & !is.na(meta_data$Mass))
meta_data$BMI[bmi_calc_index] <- (meta_data$Mass[bmi_calc_index]) / 
  (meta_data$Height[bmi_calc_index]^2)


# =============================================================================

## Remove studies with repeated measures
meta_data <- meta_data[-c(13, 26, 28, 30, 181:183, 189, 190, 218, 219, 222:225, 
                          324, 326, 349, 351, 391),]


# =============================================================================

## Hypothesis: Pressure system will influence results
# Select only studies using Emed, FootScan, or MatScan
Emed_meta_data <- filter(meta_data, System %in% "Emed")
FootScan_meta_data <- filter(meta_data, System %in% "FootScan")
MatScan_meta_data <- filter(meta_data, System %in% "MatScan")
system_meta_data <- bind_rows(Emed_meta_data, FootScan_meta_data, 
                              MatScan_meta_data)
system_meta_data$System <- droplevels(system_meta_data$System) 

# only test adult healthy subjects
system_meta_data <- filter(system_meta_data, Cohort_Type %in% "HEALTHY")
system_meta_data <- filter(system_meta_data, Age > 18)

# only test walking studies
system_meta_data <- filter(system_meta_data, Activity %in% "Walking")

# run meta-regression (run twice to check all combinations)
system_results <- meta_test(system_meta_data, regions, 
                            moderators = c("System"))
system_meta_data$System <- factor(system_meta_data$System,
                                  levels(system_meta_data$System)[c(2, 1, 3)])
system_results <- meta_test(system_meta_data, regions, 
                            moderators = c("System"))


# =============================================================================

### Hypothesis: Diabetes, Diabetes Neuropathy, Age, BMI will influence results
## EMED Data
# select healthy subjects
healthy_emed_data <- filter(Emed_meta_data, Cohort_Type %in% "HEALTHY")
healthy_emed_data <- filter(healthy_emed_data, Age > 18) # adults
healthy_emed_data <- filter(healthy_emed_data, 
                            Activity %in% "Walking") # walking

# select diabetic subjects
diabetes_emed_data <- filter(Emed_meta_data, Cohort_Type %in% "DIABETES")
neuro_index <- which(diabetes_emed_data$Cohort_subgroup == "NEUROPATHY")  
levels(diabetes_emed_data$Cohort_Type) <- c(levels(diabetes_emed_data$Cohort_Type), 
                                            "NEUROPATHY")
diabetes_emed_data$Cohort_Type[neuro_index] <- "NEUROPATHY"

# combine healthy and diabetic groups
group_meta_data_emed <- bind_rows(diabetes_emed_data, healthy_emed_data)
group_meta_data_emed$Cohort_Type <- as.factor(group_meta_data_emed$Cohort_Type)

# run meta regression
diabetes_results_emed <- meta_test(group_meta_data_emed, regions, 
                                   moderators = c("Cohort_Type", "Age", 
                                                  "BMI", "Sex_Perc"))
group_meta_data_emed$Cohort_Type <- factor(group_meta_data_emed$Cohort_Type,
                                           levels(group_meta_data_emed$Cohort_Type)[c(2, 1, 3)])
diabetes_results_emed <- meta_test(group_meta_data_emed, regions, 
                                   moderators = c("Cohort_Type", "Age", 
                                                  "BMI", "Sex_Perc"))
## FootScan data
# select healthy subjects
healthy_fs_data <- filter(FootScan_meta_data, Cohort_Type %in% "HEALTHY")
healthy_fs_data <- filter(healthy_fs_data, Age > 18) # adults
healthy_fs_data <- filter(healthy_fs_data, 
                                Activity %in% "Walking") # walking

# select diabetic subjects
diabetes_fs_data <- filter(FootScan_meta_data, Cohort_Type %in% "DIABETES")
neuro_index <- which(diabetes_fs_data$Cohort_subgroup == "NEUROPATHY")  
levels(diabetes_fs_data$Cohort_Type) <- c(levels(diabetes_fs_data$Cohort_Type),
                                                "NEUROPATHY")
diabetes_fs_data$Cohort_Type[neuro_index] <- "NEUROPATHY"

group_meta_data_fs <- bind_rows(diabetes_fs_data, healthy_fs_data)
group_meta_data_fs$Cohort_Type <- as.factor(group_meta_data_fs$Cohort_Type)

# run meta regression
diabetes_results_FootScan <- meta_test(group_meta_data_fs, regions_fs, 
                                   moderators = c("Cohort_Type", "Age", 
                                                  "BMI", "Sex_Perc"))
group_meta_data_fs$Cohort_Type <- factor(group_meta_data_fs$Cohort_Type,
                                         levels(group_meta_data_fs$Cohort_Type)[c(2, 1, 3)])
diabetes_results_FootScan <- meta_test(group_meta_data_fs, regions_fs, 
                                       moderators = c("Cohort_Type", "Age", 
                                                      "BMI", "Sex_Perc"))


# =============================================================================

## Hypothesis: Age, BMI, and sex will influence results (systems without enough
# cohorts for cohort analysis)

# select only MatScan studies on healthy adults
healthy_MatScan_data <- filter(MatScan_meta_data, Cohort_Type %in% "HEALTHY")
healthy_MatScan_data <- filter(healthy_MatScan_data, Age > 18)

# only test walking studies
healthy_MatScan_data <- filter(healthy_MatScan_data, Activity %in% "Walking")

# run meta regression
healthy_MatScan_results <- meta_test(healthy_MatScan_data, regions, 
                                     moderators = c("Age", "BMI", "Sex_Perc"))


# =============================================================================

## Plots for figures
# plot Hindfoot vs Sex
g <- ggplot(group_meta_data_emed, aes(x = Sex_Perc, y = RF_PP), group = Cohort_Type)
g <- g + geom_point(na.rm = TRUE, aes(colour = Cohort_Type),
                    size = 2)
g <- g + geom_smooth(method = "lm", se = TRUE, na.rm = TRUE, colour = "Grey50")
g <- g + scale_x_continuous(limits = c(0, 100))
g <- g + theme_bw()
g <- g + theme(legend.background = element_rect(colour = "black"),
               legend.title = element_text(face = "bold"),
               legend.position = c(0.8, 0.83))
g <- g + xlab("Females in Cohort (%)") + ylab("Hindfoot Peak Pressure (kPa)")
g <- g + labs(colour = "Cohort")
g

ggsave("Figure_3c.png", g, height = 4, width = 5, dpi = 300)

# plot MF vs BMI
g <- ggplot(group_meta_data_emed, aes(x = BMI, y = MF_PP), group = Cohort_Type)
g <- g + geom_point(na.rm = TRUE, aes(colour = Cohort_Type), size = 2)
g <- g + geom_smooth(method = "lm", se = TRUE, na.rm = TRUE, colour = "Grey50")
g <- g + scale_x_continuous(limits = c(22, 35))
g <- g + theme_bw()
g <- g + theme(legend.background = element_rect(colour = "black"),
               legend.title = element_text(face = "bold"),
               legend.position = c(0.8, 0.2))
g <- g + xlab(bquote('BMI ('*kg/m^2*')')) + ylab("Midfoot Peak Pressure (kPa)")
g <- g + labs(colour = "Cohort")
g

ggsave("Figure_3a.png", g, height = 4, width = 5, dpi = 300)

## Plot MT1 vs age
g <- ggplot(group_meta_data_emed, aes(x = Age, y = M1_PP), group = Cohort_Type)
g <- g + geom_point(na.rm = TRUE, aes(colour = Cohort_Type), size = 2)
g <- g + geom_smooth(method = "lm", se = TRUE, na.rm = TRUE, colour = "Grey50")
#g <- g + scale_x_continuous(limits = c(22, 35))
g <- g + theme_bw()
g <- g + theme(legend.background = element_rect(colour = "black"),
               legend.title = element_text(face = "bold"),
               legend.position = c(0.2, 0.8))
g <- g + xlab("Age (years)") + ylab("MTH1 Peak Pressure (kPa)")
g <- g + labs(colour = "Cohort")
g

ggsave("Figure_3b.png", g, height = 4, width = 5, dpi = 300)

## Plot HEALTHY, DIABETES, NEURO
g <- ggplot(group_meta_data_emed, aes(x = Cohort_Type, y = M1_PP, fill = Cohort_Type))
g <- g + geom_boxplot(na.rm = TRUE)
g <- g + theme_bw()
g <- g + theme(legend.position = "none")
g <- g + xlab("Cohort Type") + ylab("MTH1 Peak Pressure (kPa)")
g

ggsave("Figure_4.png", g, height = 4, width = 5, dpi = 300)


# =============================================================================

## check numbers for abstract and full text review
abstract_ws <- read_csv(paste0("C:/Users/telfe/Dropbox/My_Projects/", 
                               "Plantar_Pressure_Review/Plantar_Pressure_Review/", 
                               "Abstract_Plantar_Pressure_Worksheet.csv"))

after_review <- abstract_ws %>% filter(English == "Y") %>% 
  filter(Original == "Y" ) %>% filter(Human == "Y") %>%
  filter(Case_study == "N") %>% filter(Pressure_Measured == "Y") %>%
  filter(In_shoe_or_barefoot == c("BF", "BF/IS")) %>%
  filter(Walking_or_running == "Walking")

not_english <- abstract_ws %>% filter(English == "Y")
nrow(abstract_ws) - nrow(not_english)
not_original <- not_english %>% filter(Original == "Y")
nrow(not_english) - nrow(not_original)
not_human <- not_original %>% filter(Human == "Y")
nrow(not_original) - nrow(not_human)
not_case <- not_human %>% filter(Case_study == "N")
nrow(not_human) - nrow(not_case)
not_press <- not_case %>% filter(Pressure_Measured == "Y")
nrow(not_case) - nrow(not_press)
not_bare <- not_press %>% filter(In_shoe_or_barefoot == c("BF", "BF/IS"))
nrow(not_press) - nrow(not_bare)
not_walk <- not_bare %>% filter(Walking_or_running == "Walking")
nrow(not_bare) - nrow(not_walk)

# Number of cohorts included in analysis
numbers <- nrow(union(system_meta_data, group_meta_data_emed,
                group_meta_data_fs))

# number of papers included in the analysis
papers <- unique(c(diabetes_emed_data$Paper_No, diabetes_fs_data$Paper_No,
                   healthy_emed_data$Paper_No, healthy_fs_data$Paper_No, 
                   healthy_MatScan_data$Paper_No))

# number of individuals in system analysis
system_n <- sum(system_meta_data$Number)


# =============================================================================

## Make forest plots
# Set up image to save
png(filename = "Forest_Cohorts.png", units = "in", width = 3.5, height = 4.5, 
    pointsize = 12, res = 300)

# decrease margins so the full space is used
par(mar = c(4,4,1,2))

# set up forest plot (with 2x2 table counts added; rows argument is used
# to specify exactly in which rows the outcomes will be plotted)
forest(diabetes_results[[1]], xlab = "Peak Pressure (kPa)", addfit = FALSE, 
       refline = NA)

# set font expansion factor (as in forest() above) and use bold italic
# font and save original settings in object 'op'
op <- par(cex = 0.4, font = 4)

# add text for the subgroups
text(-6, c(15.5, 23.5, 41.5), pos = 4, c("Healthy", "KOA", "Medial KOA"))

# switch to bold font
par(font = 2)

# add column headings to the plot
text(-6, 46, "Author(s) and Year", pos = 4)
text(10, 46, "KAM (%BW*H) [95% CI]", pos = 2)

# set par back to the original settings
par(op)

# fit random-effects model in the three subgroups
res_HEALTHY <- rma(yi, vi, data = PiG_meta_data, subset = (Cohort_type == "HEALTHY"), 
                   method = "REML")
res_DIABETES <- rma(yi, vi, data = PiG_meta_data, subset = (Cohort_type == "DIABETES"), 
               method = "REML")
res_NEUROPATHY <- rma(yi, vi, data = PiG_meta_data, subset = (Cohort_type == "NEUROPATHY"), 
                   method = "REML")

# add summary polygons for the three subgroups
addpoly(res_HEALTHY, row =  0.5, cex = 0.4, mlab = "RE Model for Subgroup")
addpoly(res_DIABETES, row = 18.5, cex = 0.4, mlab = "RE Model for Subgroup")
addpoly(res_NEUROPATHY, row = 26.5, cex = 0.4, mlab = "RE Model for Subgroup")

dev.off()


# set up forest plot (with 2x2 table counts added; rows argument is used
# to specify exactly in which rows the outcomes will be plotted)
forest(system_results[[5]], xlab = "Peak Pressure (kPa)", 
       mlab = "KAM (%BW*H)", addfit = FALSE, refline = NA)


###############################################################################
# =============================================================================
# END OF CODE 
# =============================================================================
###############################################################################
