# Plantar pressure meta-regression analysis
# Author: Scott Telfer
# Email: scott.telfer@gmail.com
# Last updated: 2017/11/15

# =============================================================================

## Import libraries
source("C:/Users/telfe/Dropbox/R Code/pkgTest.R")
packages <- c("metafor", "readr", "ggplot2", "dplyr")
lapply(packages, pkgTest)


# =============================================================================

## Helper functions
regions <- c("FF_PP", "MF_PP", "RF_PP", "M1_PP", "M2_PP", "M3_PP", "M4_PP", 
             "M5_PP", "HLX_PP")
meta_test <- function(meta_df, regions, moderators) {
  meta_test_results <- list()
  for (i in seq_along(regions)) {
    # filter for region
    meta_df_es <- meta_df %>% filter_(!is.na(regions[i]))
    
    # determine effect sizes
    meta_df_es <- escalc(measure = "MN", mi = get(regions[i]), 
                         sdi = get(paste0(regions[i], "_SD")), 
                         ni = Number, data = meta_df, 
                         slab = paste(First_Author, Year))
    
    # run meta regression
    f <- paste0("~ ", paste0(moderators, collapse = " + "))
    system_res_ME <- rma(yi, vi, mods = as.formula(f), data = meta_df_es, 
                         method = "REML")
    
    # save results
    meta_test_results[[i]] <- system_res_ME
  }
  
  # return list of model results
  return(meta_test_results)
}


# =============================================================================

## Import data sheet
meta_data <- read_csv(paste0("C:/Users/telfe/Dropbox/My_Projects/", 
                             "Plantar_Pressure_Review/Plantar_Pressure_Review/", 
                             "PP_meta_data.csv"))

# remove empty rows (sometimes generated by excel)
meta_data <- meta_data[rowSums(is.na(meta_data))!=ncol(meta_data), ]


# Convert relevant columns to factors
cols <- c("Repeated", "Cohort_Type", "Footwear", "Activity", "System")
meta_data[cols] <- lapply(meta_data[cols], factor)


# =============================================================================

## Visualise raw data to check for issues
# Number of participants
boxplot(meta_data$Number, main = "Number of Participants")
summary(meta_data$Number)

# Percentage of participants who are female
boxplot(meta_data$Sex_Perc, main = "Percentage Female")
summary(meta_data$Sex_Perc)

# Age
boxplot(meta_data$Age, main = "Age")
summary(meta_data$Age)

# Height
boxplot(meta_data$Height, main = "Height")
summary(meta_data$Height)

# Mass
boxplot(meta_data$Mass, main = "Weight")
summary(meta_data$Mass)

# BMI
boxplot(meta_data$BMI, main = "BMI")
summary(meta_data$BMI)

# Speed
meta_data$Speed[meta_data$Speed == "SS"] <- NA # replace SS with NA
meta_data$Speed <- as.numeric(meta_data$Speed)
boxplot(meta_data$Speed, main = "Speed")
summary(meta_data$Speed)

## Visualize data to check for issues with disecrete variables
# Cohort type
barplot(table(meta_data$Cohort_Type))
levels(meta_data$Cohort_Type)

# Repeated
barplot(table(meta_data$Repeated))
levels(meta_data$Repeated)

# Footwear
barplot(table(meta_data$Footwear))
levels(meta_data$Footwear)

# System
barplot(table(meta_data$System))
levels(meta_data$System)


# =============================================================================

## data calculations
# BMI from height and weight
bmi_calc_index <- which(is.na(meta_data$BMI) & !is.na(meta_data$Height) 
                        & !is.na(meta_data$Mass))
meta_data$BMI[bmi_calc_index] <- (meta_data$Mass[bmi_calc_index]) / 
  (meta_data$Height[bmi_calc_index]^2)


# =============================================================================

## Remove studies with repeated measures
meta_data <- meta_data[c(1:181, 185:222, 227:324, 327:nrow(meta_data)),]


# =============================================================================

## Hypothesis: Pressure system will influence results
# Select only studies using Emed, FootScan, or MatScan
Emed_meta_data <- filter(meta_data, System %in% "Emed")
FootScan_meta_data <- filter(meta_data, System %in% "FootScan")
MatScan_meta_data <- filter(meta_data, System %in% "MatScan")
system_meta_data <- bind_rows(Emed_meta_data, FootScan_meta_data, 
                              MatScan_meta_data)
system_meta_data$System <- droplevels(system_meta_data$System) 

# only test adult healthy subjects
system_meta_data <- filter(system_meta_data, Cohort_Type %in% "HEALTHY")
system_meta_data <- filter(system_meta_data, Age > 18)

# only test walking studies
system_meta_data <- filter(system_meta_data, Activity %in% "Walking")

# run meta-regression (run twice to check all combinations)
system_results <- meta_test(system_meta_data, regions, 
                            moderators = c("System"))
system_meta_data$System <- factor(system_meta_data$System,
                                  levels(system_meta_data$System)[c(2, 1, 3)])
system_results <- meta_test(system_meta_data, regions, 
                            moderators = c("System"))


# =============================================================================

## Hypothesis: Age, BMI, and sex will influence results
# select only emed studies on healthy adults
healthy_emed_data <- filter(Emed_meta_data, Cohort_Type %in% "HEALTHY")
healthy_emed_data <- filter(healthy_emed_data, Age > 18)

# only test walking studies
healthy_emed_data <- filter(healthy_emed_data, Activity %in% "Walking")

# run meta regression
healthy_emed_results <- meta_test(healthy_emed_data, regions, 
                                  moderators = c("Age", "BMI", "Sex_Perc"))


# =============================================================================

## Hypothesis: Diabetes, Diabetes Neuropathy, Age, BMI will influence results
# select healthy and diabetic subjects
diabetes_emed_data <- filter(Emed_meta_data, Cohort_Type %in% "DIABETES")
neuro_index <- which(diabetes_emed_data$Cohort_subgroup == "NEUROPATHY")  
levels(diabetes_emed_data$Cohort_Type) <- c(levels(diabetes_emed_data$Cohort_Type), "NEUROPATHY")
diabetes_emed_data$Cohort_Type[neuro_index] <- "NEUROPATHY"

group_meta_data <- bind_rows(diabetes_emed_data, healthy_emed_data)
group_meta_data$Cohort_Type <- as.factor(group_meta_data$Cohort_Type)
group_meta_data$Cohort_Type <- factor(group_meta_data$Cohort_Type,
                                      levels(group_meta_data$Cohort_Type)[c(2, 1, 3)])

# run meta regression
diabetes_results <- meta_test(group_meta_data, regions, 
                              moderators = c("Cohort_Type", "Age", "BMI", "Sex_Perc"))


# =============================================================================

## Plots for figures
# plot Hindfoot vs Sex
g <- ggplot(group_meta_data, aes(x = Sex_Perc, y = RF_PP), group = Cohort_Type)
g <- g + geom_point(na.rm = TRUE, aes(colour = Cohort_Type),
                    size = 2)
g <- g + geom_smooth(method = "lm", se = TRUE, na.rm = TRUE, colour = "Grey50")
g <- g + scale_x_continuous(limits = c(0, 100))
g <- g + theme_bw()
g <- g + theme(legend.background = element_rect(colour = "black"),
               legend.title = element_text(face = "bold"),
               legend.position = c(0.8, 0.83))
g <- g + xlab("Females in Cohort (%)") + ylab("Hindfoot Peak Pressure (kPa)")
g <- g + labs(colour = "Cohort")
g

ggsave("Figure_3c.png", g, height = 4, width = 5, dpi = 300)

# plot MF vs BMI
g <- ggplot(group_meta_data, aes(x = BMI, y = MF_PP), group = Cohort_Type)
g <- g + geom_point(na.rm = TRUE, aes(colour = Cohort_Type), size = 2)
g <- g + geom_smooth(method = "lm", se = TRUE, na.rm = TRUE, colour = "Grey50")
g <- g + scale_x_continuous(limits = c(22, 35))
g <- g + theme_bw()
g <- g + theme(legend.background = element_rect(colour = "black"),
               legend.title = element_text(face = "bold"),
               legend.position = c(0.8, 0.2))
g <- g + xlab(bquote('BMI ('*kg/m^2*')')) + ylab("Midfoot Peak Pressure (kPa)")
g <- g + labs(colour = "Cohort")
g

ggsave("Figure_3a.png", g, height = 4, width = 5, dpi = 300)

## Plot MT1 vs age
g <- ggplot(group_meta_data, aes(x = Age, y = M1_PP), group = Cohort_Type)
g <- g + geom_point(na.rm = TRUE, aes(colour = Cohort_Type), size = 2)
g <- g + geom_smooth(method = "lm", se = TRUE, na.rm = TRUE, colour = "Grey50")
#g <- g + scale_x_continuous(limits = c(22, 35))
g <- g + theme_bw()
g <- g + theme(legend.background = element_rect(colour = "black"),
               legend.title = element_text(face = "bold"),
               legend.position = c(0.2, 0.8))
g <- g + xlab("Age (years)") + ylab("MTH1 Peak Pressure (kPa)")
g <- g + labs(colour = "Cohort")
g

ggsave("Figure_3b.png", g, height = 4, width = 5, dpi = 300)


# =============================================================================

## check numbers for abstract and full text review
abstract_ws <- read_csv(paste0("C:/Users/telfe/Dropbox/My_Projects/", 
                               "Plantar_Pressure_Review/Plantar_Pressure_Review/", 
                               "Abstract_Plantar_Pressure_Worksheet.csv"))

after_review <- abstract_ws %>% filter(English == "Y") %>% 
  filter(Original == "Y" ) %>% filter(Human == "Y") %>%
  filter(Case_study == "N") %>% filter(Pressure_Measured == "Y") %>%
  filter(In_shoe_or_barefoot == c("BF", "BF/IS")) %>%
  filter(Walking_or_running == "Walking")

not_english <- abstract_ws %>% filter(English == "Y")
not_original <- not_english %>% filter(Original == "Y")
not_human <- not_original %>% filter(Human == "Y")
not_case <- not_human %>% filter(Case_study == "N")
not_press <- not_case %>% filter(Pressure_Measured == "Y")
not_bare <- not_press %>% filter(In_shoe_or_barefoot == c("BF", "BF/IS"))
not_walk <- not_bare %>% filter(Walking_or_running == "Walking")


# =============================================================================

## Check number of cohorts/papers used in analysis
full_set <- union(system_meta_data, diabetes_emed_data)
no_of_unique_papers <- length(unique(full_set$Paper_No))
no_subjects_system <- sum(system_meta_data$Number)


###############################################################################
# =============================================================================
# END OF CODE 
# =============================================================================
###############################################################################
